import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { getD1 } from "../../../../db/d1";
export const dynamic = "force-dynamic";
type Params = Promise<{ id: string }>;
type Query = Promise<{ date?: string }>;
async function stop(id: string) { return getD1().prepare(`SELECT s.id, s.name, s.code, s.latitude, s.longitude, a.name AS agencyName, a.attribution, a.license_name AS licenseName, a.license_url AS licenseUrl, a.feed_url AS feedUrl, a.updated_at AS updatedAt FROM bus_stops s JOIN bus_agencies a ON a.id = s.agency_id WHERE s.id = ?1`).bind(id).first<Record<string, string | number | null>>(); }
export async function generateMetadata({ params }: { params: Params }): Promise<Metadata> { const data = await stop((await params).id); return data ? { title: `${data.name} バス停の時刻表`, description: `${data.name}バス停（${data.agencyName}）の路線バス時刻表・行き先を確認できます。`, alternates: { canonical: `/local-bus/stops/${encodeURIComponent(String(data.id))}` } } : {}; }
export default async function StopPage({ params, searchParams }: { params: Params; searchParams: Query }) {
  const data = await stop((await params).id); if (!data) notFound();
  // 検索画面で選んだ乗車日をそのまま引き継ぐ。不正値・未指定は当日にフォールバックする。
  const date = compactDate((await searchParams).date) || japanDate(), weekday =["sunday", "monday", "tuesday", "wednesday", "thursday", "friday", "saturday"][new Date(`${date.slice(0,4)}-${date.slice(4,6)}-${date.slice(6,8)}T12:00:00+09:00`).getUTCDay()];
  const departures = await getD1().prepare(`SELECT st.departure_time AS departureTime, t.headsign, l.short_name AS lineShortName, l.long_name AS lineLongName, l.color, a.name AS agencyName FROM bus_stop_times st JOIN bus_trips t ON t.id=st.trip_id JOIN bus_lines l ON l.id=t.line_id JOIN bus_agencies a ON a.id=l.agency_id LEFT JOIN bus_calendars c ON c.id=t.service_id WHERE st.stop_id=?1 AND (((c.start_date<=?2 AND c.end_date>=?2 AND c.${weekday}=1) AND NOT EXISTS (SELECT 1 FROM bus_calendar_dates x WHERE x.service_id=t.service_id AND x.date=?2 AND x.exception_type=2)) OR EXISTS (SELECT 1 FROM bus_calendar_dates x WHERE x.service_id=t.service_id AND x.date=?2 AND x.exception_type=1)) ORDER BY st.departure_time LIMIT 200`).bind(data.id, date).all();
  const jsonLd={"@context":"https://schema.org","@type":"BusStop",name:data.name,geo:{"@type":"GeoCoordinates",latitude:data.latitude,longitude:data.longitude},provider:{"@type":"Organization",name:data.agencyName}};
  return <main className="stop-page"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(jsonLd)}}/><header className="results-nav"><a className="brand" href="/"><span>N</span>NOLU</a><a href="/local-bus">停留所検索</a></header><section className="stop-hero"><div className="directory-shell"><nav><a href="/">ホーム</a> / <a href="/local-bus">路線バス</a> / {String(data.name)}</nav><span className="kicker">BUS STOP TIMETABLE</span><h1>{String(data.name)}</h1><p>{String(data.agencyName)}{data.code ? `・停留所コード ${data.code}`:""}</p></div></section><section className="directory-shell stop-content"><header><div><h2>{date===japanDate()?"本日の発車時刻":"指定日の発車時刻"}</h2><p>{date.slice(0,4)}年{date.slice(4,6)}月{date.slice(6,8)}日・予定時刻</p></div><a href={`https://www.google.com/maps?q=${data.latitude},${data.longitude}`} target="_blank" rel="noreferrer">地図で見る →</a></header><div className="departure-list">{departures.results.map((item,index)=><article key={`${item.departureTime}-${index}`}><time>{String(item.departureTime).slice(0,5)}</time><i style={{background:item.color?`#${item.color}`:"#174c3b"}}/><div><b>{String(item.lineShortName||item.lineLongName||"路線バス")}</b><span>{String(item.headsign||"行き先情報なし")}</span><small>{String(item.agencyName)}</small></div></article>)}{!departures.results.length&&<p className="admin-empty">この日の運行時刻は登録されていません。運休日またはデータ更新中の可能性があります。</p>}</div><aside className="data-source-note"><h2>出典・ライセンス</h2><p>{String(data.attribution||data.agencyName)}。最終更新 {new Date(Number(data.updatedAt)).toLocaleDateString("ja-JP")}。</p>{data.licenseUrl?<a href={String(data.licenseUrl)} target="_blank" rel="noreferrer">{String(data.licenseName||"利用条件")} →</a>:null}{data.feedUrl?<a href={String(data.feedUrl)} target="_blank" rel="noreferrer">GTFS配布元 →</a>:null}</aside></section></main>;
}
function japanDate(){return new Intl.DateTimeFormat("ja-JP",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date()).replaceAll("/","");}
/** "2026-08-11" と "20260811" の両方を YYYYMMDD に正規化する。不正値は空文字。 */
function compactDate(value:string|undefined){const digits=(value||"").replaceAll("-","");return /^\d{8}$/.test(digits)?digits:"";}
